# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gstiedem <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/20 18:37:33 by gstiedem          #+#    #+#              #
#    Updated: 2018/11/20 18:54:03 by gstiedem         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

ft_display_file:
	gcc -Wall -Wextra -Werror *c -o ft_display_file

clean:
	
fclean:
	rm -f ft_display_file
